In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.2.3


Why numpy is faster than list?
- Each element in list [1,2,3] has attributes
    - Size
    - Reference Count
    - Object Type
    - Object Value
    - Discontinous memory allocation
- Each element in numpy array has:
    - Raw data
    - dtype(data type)
    - Continous memory allocation

In [6]:
a = [1,3,5]
b = [2,4,6]

In [7]:
print(a*b)

TypeError: can't multiply sequence by non-int of type 'list'

In [9]:
c = np.array(a)
d = np.array(b)
print(c*d)

[ 2 12 30]


In [10]:
e = np.array([c,d])
print(e)

[[1 3 5]
 [2 4 6]]


In [12]:
#Get Dimension
e.ndim

2

In [13]:
# Get Shape
e.shape

(2, 3)

In [22]:
#Get Type
print(e.dtype)
print(e.itemsize)

int64
8


In [24]:
f = np.array([1,2,3], dtype = 'int16')
print(f)
print(f.dtype)
#Element Size
print(f.itemsize)
#Get total Size
print(f.nbytes)

[1 2 3]
int16
2
6


**Accessing/Changing elements in rows , columns**

In [26]:
a = np.array([[1,2,3,4,5,6,7,8],[11,12,13,14,15,16,17,18]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [11 12 13 14 15 16 17 18]]


In [27]:
print(a[0])

[1 2 3 4 5 6 7 8]


In [33]:
print(a[:, 3])

[ 4 14]


In [34]:
print(a[0,:])

[1 2 3 4 5 6 7 8]


In [46]:
#Slicing [startindex:endindex:stepsize]
print(a[::-1,4])

[15  5]


In [47]:
a[1,4] = 100

In [48]:
print(a)

[[  1   2   3   4   5   6   7   8]
 [ 11  12  13  14 100  16  17  18]]


In [49]:
a[0, 0:2] = [99,98]

In [50]:
print(a)

[[ 99  98   3   4   5   6   7   8]
 [ 11  12  13  14 100  16  17  18]]


**3-D array**

In [55]:
a = np.array([
    [[1,2],
     [3,4]],
    [[5,6],
     [7,8]],
    [[9,10],
     [11,12]]
])

In [56]:
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [65]:
print(a[:,:,0])

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [68]:
#replace
a[:,:,0] = 1

In [69]:
print(a)

[[[  1  99]
  [  1 102]]

 [[  1   6]
  [  1   8]]

 [[  1  10]
  [  1  12]]]


**Initialyzing Different types of Arrays**

In [81]:
#All 0s
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [83]:
#All 1s
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [90]:
#Any number
np.full((2,2), 5)
np.full((2), 5).reshape(2,1)

array([[5],
       [5]])

In [91]:
#random decimal number
np.random.rand(2,9)

array([[0.19044987, 0.70022403, 0.85133182, 0.96591634, 0.31493695,
        0.1530805 , 0.96010399, 0.18485488, 0.29044824],
       [0.14894916, 0.08905758, 0.54511489, 0.82213654, 0.29285108,
        0.94725823, 0.00207507, 0.31152489, 0.04253897]])

In [96]:
#random values of defined shape
np.random.random_sample(e.shape)

array([[0.50195137, 0.183317  , 0.34528826],
       [0.51049555, 0.07919231, 0.71481054]])

In [99]:
#Random integer values
np.random.randint(4,7, size=(4,4), dtype = 'int16')

array([[6, 6, 6, 5],
       [6, 4, 6, 5],
       [4, 4, 6, 4],
       [5, 6, 5, 5]], dtype=int16)

In [100]:
#identiy matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
arr = np.array([1,2,3])
repeat = np.repeat(arr,3, axis = 0)
print(repeat)

[1 1 1 2 2 2 3 3 3]


In [108]:
a = np.ones((5,5))
a[1:4,1:4] = 0
a[2,2] = 9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Copying Mechanics**

In [114]:
a = np.array([1,2,3])
b = a # b is referencing to the location of a.
b[1] = 100
a

array([  1, 100,   3])

In [115]:
a = np.array([1,2,3])
b = a.copy()
b[1] = 100
a

array([1, 2, 3])

**MATHEMATICS**

In [117]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [118]:
a + 2

array([3, 4, 5, 6])

In [119]:
a - 2

array([-1,  0,  1,  2])

In [120]:
a * 2

array([2, 4, 6, 8])

In [121]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [127]:
b = np.array([1,0,1,0])
a + b
a * b

array([1, 0, 3, 0])

In [124]:
a ** 2

array([ 1,  4,  9, 16])

In [125]:
#Take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [126]:
#Take cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

**Linear Algebra**

In [132]:
#Multiplication
a = np.ones((2,4))
print(a)

b = np.full((4,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]]


array([[8., 8.],
       [8., 8.]])

In [133]:
#Finding the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)